### ISSUE TITLE
Proposed Categories

### ISSUE THREAD

**Issue by young-steveo** [rockgolem/rockgolem.github.io#2]
We discussed predefining our blog categories, and sticking to those.

You mentioned the hierarchal structure on your post: `W & W > Design > then the specific category` I started thinking that maybe we will sometimes blog about something that's not about one of our games specifically, or possibly about more than one of our games at the same time.  With that in mind, I started thinking we could just tag the posts with the game name if needed, and drop the names from the category hierarchy.

That got me thinking that maybe we don't need a hierarchy of categories.  Just a small set of generic, global categories.  Each post lives under one category, and further taxonomy can be mapped out with tags to help find posts in the future.

So, here's my proposed Category list:
- News (launching new games, starting a beta testing phase, launching a kickstarter etc.)
- Game Design (game mechanics/design, like the card post you wrote and the W&W one I wrote)
- Art & Music (for showing off game assets and sound effects, etc.)
- Technology (Posts about architecture, code, etc.)

There may be room for 1 or two more, if you can think of anything.

Then, we can tag all of the posts however we want (including game-name tags like W&W)

**Comment by cjsaylor** [comment]
:+1: I think having a flat category setup will not only be more searchable (seo), but also nicer to look at (and not take up so much side-bar space). Tag use rather than categories for game names, etc make more sense.

**Comment by young-steveo** [comment]
Done
